### ISSUE TITLE
Following up with IIPC

### ISSUE THREAD

**Issue by cldellow** [benwills/proposal-warc-to-zstandard#1]
Hi Ben,

Have you followed up with the IIPC about this analysis? If not, would you be OK with me raising it?

I suspect it would basically boil down to me opening a ticket and asking if they'd be open to amending Annex D to recommend zstd as well as (or instead of) zlib and gathering feedback on compatibility requirements that the broader standards group would want checked before making such a change.

Thanks for this great writeup!

**Comment by benwills** [comment]
@cldellow Somehow missed this last month.

By all means feel free to follow up with them on this. I haven't touched this code in a while, but I'm glad to jump back in and help however I can.

**Comment by cldellow** [comment]
Great! I've opened https://github.com/iipc/warc-specifications/issues/53 to pursue that.
